### ISSUE TITLE
About upgrading to the latest JupyterLab (and bpmn.js)

### ISSUE THREAD

**Issue by datakurre** [PhE/jupyterlab_bpmn#1]
@bollwyvl Asking for a guidance. I’d like to migrate this plugin to the latest JupyterLab (to have bpmn.js-rendering in JupyterLite), but also be able to annotate the renderings. bpmn.js has rich customizations and annotation support, but what would be recommended way connect that to eg. pyolite?

On regular JupyterLab all this would require probably an ipywidgets widget and then figuring out an API to pass configuration for that. But maybe on JupyterLite something could be done without Python code?

**Comment by datakurre** [comment]
Or, if a renderer really gets the raw display data with data for every provided mime type, would it be ok for a renderer to expect an additional mime type payload for annotation data. So that, by default, the renderer would render just `model.data['application/bpmn+xml']`, but if there was also `model.data['application/x-bpmn-annotate']` (or something), it would apply annotations from that. And that way the rendered would both be able to render standalone BPMN files, but it would be also callable by `IPython.display` with custom annotation data?

**Comment by datakurre** [comment]
This approach seems to be working. But will be probably opinionated enough that I'll make a plugin of my own.

![jupyterlab-bpmn](https://user-images.githubusercontent.com/160447/130281517-71911701-9873-439f-9b20-00447c2490cd.png)

**Comment by datakurre** [comment]
https://pypi.org/project/jupyterlab-bpmn/

https://pypi.org/project/jupyterlab-dmn/

![output](https://user-images.githubusercontent.com/160447/130361984-9738f133-20f5-4878-afcf-f1d4998ba04c.gif)

**Comment by bollwyvl** [comment]
That's totally awesome, sorry i wasn't around (packing, moving, driving, unpacking, more driving, more unpacking, SLEEPING).

I think the MIME renderer approach is a solid first step, _especially_ if it's Someone Else's MIME Type which is documented somewhere, or spoken by some (even proprietary) application (e.g. an editor or a REST API or whatever). As a next step, you might take a feather from the `IPython.display` core stuff and make a `BMPN('...model...', '...annotation...')` convenience wrapper, too, especially if it speaks multiple flavors.

Another sneaky thing you can do (a la `vega`) is to stuff the `image/svg+xml` (or png or whatever it does) back in (alas, not to the _kernel_), so that e.g. a notebook will show _something_ even if `bpmns.js` won't load for some reason.

The next abstraction might be to take the "raw" renderer, and refactor it a bit so it can be an `ipywidgets.DOMWidget` on the backend with a `@jupyter-widgets/base:DOMWidgetModel` and `DOMWidgetView` on the frontend. This would allow you to actually get the state, clicks, selection, etc. _back_ from the user. It's totally reasonable, as a first cut, to just hand the various flavors of XML back and forth rather than trying to "widgetize" all the underlying code... though often transient things like "what am i hovering over" doesn't fit in the data model, and you have to update it.

Some examples:

- https://github.com/jupyrdf/ipyelk (doesn't have MIME... yet!)
- https://github.com/deathbeds/ipydrawio (has MIME, and document, and ipywidget)

Anyhow, next week there's a [jupyter community call](https://discourse.jupyter.org/t/jupyter-community-calls/668/68) were it would be lovely for folk to see some of this cool stuff!

**Comment by datakurre** [comment]
@bollwyvl Thanks for all the tips! About "image/svg+xml". Can a MIME renderer itself set this?

About Jupyter call. Unfortunately, I cannot commit to anything scheduled for the next two weeks :grimacing:

**Comment by datakurre** [comment]
> The mime renderer can update its data by calling .setData() on the model it is given to render. This can be used for example to add a png representation of a dynamic figure, which will be picked up by a notebook model and added to the notebook document. When using IDocumentWidgetFactoryOptions, you can update the document model by calling .setData() with updated data for the rendered MIME type. The document can then be saved by the user in the usual manner.

**Comment by datakurre** [comment]
@bollwyvl Unfortunately, just calling setData with the old data + image/svg+xml makes lab to call SVG mime renderer that replaces my custom MIME renderer output :see_no_evil:

**Comment by bollwyvl** [comment]
A bit hard to see without some linkage, but here's what [core does for vega](https://github.com/jupyterlab/jupyterlab/blob/dbdefed9db9332381fe4104bdf53ec314451951f/packages/vega5-extension/src/index.ts#L130-L133). It might be a timing or priority thing, as the vega one seems to work fine...

**Comment by datakurre** [comment]
@bollwyvl https://github.com/datakurre/jupyterlab-bpmn/commit/79267015b9f48e9f228682bfa5ae5c465e831516

But next I will look closer to vega for possible differences.

**Comment by datakurre** [comment]
@bollwyvl Thanks. It was a priority thing. Found the ranks https://github.com/jupyterlab/jupyterlab/blob/master/packages/rendermime/src/factories.ts and being before SVG was enough.

**Comment by datakurre** [comment]
But then I learned that SVG renderer is not "safe", so SVG is not rendered in all situations. Also PNG needed :)

https://github.com/jupyterlab/jupyterlab/blob/9c592fcee69915a2581ed4bdfeaddbda8bf5acb3/packages/rendermime/src/factories.ts#L52

**Comment by bollwyvl** [comment]
> SVG renderer is not "safe",

Thats too bad! So much more pleasing for diagrams!

**Comment by datakurre** [comment]
But if SVG is enough for GitHub it is enough for me https://github.com/datakurre/jupyterlab-bpmn/blob/main/examples/example.ipynb :)

**Comment by bollwyvl** [comment]
Yeah, that's delicious.
